# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 959722348736ad84ece1128db6290712b9661c98ba87609ab28b3ac2db23671690e690dd26f1d1a17b03cd1ce0a3709228b6c9a0db72ffe561f04297c0092637
  facebook_app: 461738674223616
  facebook_secret: 7776fe483060bd1a31df4ab10f471bed
  windows_app: 054023e5-a799-4b33-92c4-c1efe15877d4
  windows_secret: shmuTDCU37_~zelINF752==
  google_app: 283756780051-94peltr38q57e9jq7ic0ieojeidim8bq.apps.googleusercontent.com 
  google_secret: iMN4WDY3N0OfX9ToKXgySHUm 

test:
  secret_key_base: a037a36ea8981437d30e7bf82223edf894e1206bae9cc41943c31ebe3c92ab1cc95f3e6de562c3ed1a9e2cb07ac143cd176601f0c5c50a56ff1e5790ea12601e
  facebook_app: 461738674223616
  facebook_secret: 7776fe483060bd1a31df4ab10f471bed
  windows_app: 054023e5-a799-4b33-92c4-c1efe15877d4
  windows_secret: shmuTDCU37_~zelINF752==
  google_app: 283756780051-94peltr38q57e9jq7ic0ieojeidim8bq.apps.googleusercontent.com 
  google_secret: iMN4WDY3N0OfX9ToKXgySHUm 

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app: <%= ENV['FACEBOOK_KEY'] %>
  facebook_secret: <%= ENV['FACEBOOK_SECRET'] %>
  windows_app: <%= ENV['LINKEDIN_KEY'] %>
  windows_secret: <%= ENV['LINKEDIN_SECRET'] %>
  google_app: <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>