#%RAML 0.8
title: Steroids Data
mediaType: application/json
baseUri: https://rest-api.appgyver.com/v1

traits:
    - securedBySteroidsApiKey:
        headers:
          steroidsApiKey:
            type: string
            example: exampleapikey
            default: a24729329af5a10bbd7046b8bfc221ad58bb49849494f664ddcf6c958ebc5d98
          steroidsAppId:
            type: integer
            example: 1234
            default: 82656
  
schemas:
  - person_collection: '{"$schema":"http://json-schema.org/schema","title":"person collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical person representation","properties":{"name":{"type":"string"},"surname":{"type":"string"},"nickname":{"type":"string"}},"required":[]}}}}'
  - person_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical person representation","properties":{"object":{"type":"object","properties":{"name":{"type":"string"},"surname":{"type":"string"},"nickname":{"type":"string"}},"required":[]}}}'
  - journey_collection: '{"$schema":"http://json-schema.org/schema","title":"journey collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical journey representation","properties":{"name":{"type":"string"},"closed":{"type":"string"}},"required":[]}}}}'
  - journey_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical journey representation","properties":{"object":{"type":"object","properties":{"name":{"type":"string"},"closed":{"type":"string"}},"required":[]}}}'
  - cost_collection: '{"$schema":"http://json-schema.org/schema","title":"cost collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical cost representation","properties":{"date":{"type":"string"},"name":{"type":"string"},"id_journey":{"type":"string"}},"required":[]}}}}'
  - cost_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical cost representation","properties":{"object":{"type":"object","properties":{"date":{"type":"string"},"name":{"type":"string"},"id_journey":{"type":"string"}},"required":[]}}}'
  - pay_collection: '{"$schema":"http://json-schema.org/schema","title":"pay collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical pay representation","properties":{"value":{"type":"string"},"id_cost":{"type":"string"},"id_person":{"type":"string"}},"required":[]}}}}'
  - pay_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical pay representation","properties":{"object":{"type":"object","properties":{"value":{"type":"string"},"id_cost":{"type":"string"},"id_person":{"type":"string"}},"required":[]}}}'
  - journeyspeople_collection: '{"$schema":"http://json-schema.org/schema","title":"journeyspeople collection","type":"object","properties":{"objects":{"type":"array","items":{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical journeyspeople representation","properties":{"id_journey":{"type":"string"},"id_person":{"type":"string"}},"required":[]}}}}'
  - journeyspeople_member: '{"$schema":"http://json-schema.org/schema","type":"object","description":"The canonical journeyspeople representation","properties":{"object":{"type":"object","properties":{"id_journey":{"type":"string"},"id_person":{"type":"string"}},"required":[]}}}'

resourceTypes:
  - dolan_db_collection:
      usage: This resourceType should be used for any collection of items
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "collection"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "objects"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_collection # e.g cars
      post:
        description: |
          {
            "action": "create",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car

  - dolan_db_member:
      usage: This resourceType should be used for any built.io item
      is: [ securedBySteroidsApiKey ]
      get:
        description: |
          {
            "action": "find"
          }
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member # e.g. car
      put:
        description: |
          {
            "action": "update",
            "rootKey": "object"
          }
        body:
          application/json:
            schema: <<resourcePathName>>_member
        responses:
          200:
            description: |
              {
                "rootKey": "object"
              }
            body:
              application/json:
                schema: <<resourcePathName>>_member
      delete:
        description: |
          {
            "action": "destroy"
          }
        responses:
          200:


/person:
  description: |
    {
      "resourceName": "person",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member

/journey:
  description: |
    {
      "resourceName": "journey",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member

/cost:
  description: |
    {
      "resourceName": "cost",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member

/pay:
  description: |
    {
      "resourceName": "pay",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member

/journeyspeople:
  description: |
    {
      "resourceName": "journeyspeople",
      "identifierKey": "id"
    }
  type: dolan_db_collection
  /{id}:
    type: dolan_db_member


